Document: firmware-mod-kit
Title: Debian firmware-mod-kit Manual
Author: <insert document author here>
Abstract: This manual describes what firmware-mod-kit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/firmware-mod-kit/firmware-mod-kit.sgml.gz

Format: postscript
Files: /usr/share/doc/firmware-mod-kit/firmware-mod-kit.ps.gz

Format: text
Files: /usr/share/doc/firmware-mod-kit/firmware-mod-kit.text.gz

Format: HTML
Index: /usr/share/doc/firmware-mod-kit/html/index.html
Files: /usr/share/doc/firmware-mod-kit/html/*.html
